# Generated by Django 4.2.2 on 2023-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_medico_especialidade_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
