# Generated by Django 4.2.2 on 2023-07-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_diagnostico_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='prontuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='main.prontuario'),
        ),
    ]
